name: Trigger auto deployment for shop-app-thivy-ui

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "ui/azure-shop-app/**"
      - ".github/workflows/azure-shop-app.yml"

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SHOPAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/ui/azure-shop-app
          registryUrl: ${{SHOPAPP_REGISTRY_URL}}
          registryUsername: ${{ secrets.SHOPAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SHOPAPP_REGISTRY_PASSWORD }}
          containerAppName: shop-app-ui
          resourceGroup: ${{SHOPAPP_RESOURCE_GROUP}}
          imageToBuild: ${{SHOPAPP_REGISTRY_URL}}/shop-app-ui:${{ github.sha }}
          dockerfilePath: Dockerfile
